version: '2'
services:
    bcine30-app:
        image: bcine30
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bcine30-mysql:3306/bcine30?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bcine30-mysql:
        extends:
            file: mysql.yml
            service: bcine30-mysql
